	<HEADER id='header'>
		<DIV id='banner'> 
			<DIV id='bannerBox1' class='darkColorFill'>
				<IMG src='./img/ct1.gif' alt='' />
			</DIV>
			<DIV id='bannerBox2' class='darkColorFill'>
				
			</DIV>
			<DIV id='bannerBox3' class='medColorFill'>
				
			</DIV>
			<DIV id='bannerBox4' class='lightColorFill'>
				
			</DIV>
			<DIV id='bannerBox5'>
				<SPAN id='banner5TitleLinks'>
					<!-- Replace with server-scoped SPAN for user-cusomization -->
					<A class='navbar' href='http://sourceforge.net/projects/conspectis/' title='ConspectIS @ SourceForge'>@SourceForge</A> | 
					<A class='navbar' href='http://code.google.com/p/conspectis' title='ConspectIS @ GoogleCode'>@GoogleCode</A> | 
					<A class='navbar' href='http://www.facebook.com/Conspectis' title='ConspectIS @ Facebook'>@Facebook</A> |
					<A class='navbar' href='http://twitter.com/conspectis' title='ConspectIS @ Twitter'>@Twitter</A> | 
					<A class='navbar' href='license.aspx' title='View the License'>License</A> | 
					<A class='navbar' href='https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=BWYP3R9EKMRP8' title='Donate to the ConspectIS Project'>Donate</A>  
				</SPAN>
				<BR/>
				<BR/>
				<IMG src='./img/ConspectISLogo60.png' style='vertical-align:top;' height='50' alt=''/>
				<SPAN id='systemTitleText'>
					<!-- Replace with server-scoped SPAN for user-cusomization -->
					ConspectIS DCM
				</SPAN>
				<BR/>
				<SPAN id='localization' style='vertical-align:bottom;'>
					<!-- Replace with server-scoped SPAN for user-cusomization -->
					Localization tagline or catchy phrase here ...
				</SPAN>
			</DIV>
			<DIV id='bannerBox6' style='vertical-align:bottom;'>
				
			</DIV>
			<DIV id='bannerBox7'>
				<SPAN id='banner7TitleLinks'>
					<!-- Replace with server-scoped SPAN for user-cusomization -->
					<IMG src='./img/grey_arr.gif' alt='' width='14' height='10'> 
					[ <A class='navbar' href='' title=''>SideLink1</A> ]
					<BR/>
					<IMG src='./img/grey_arr.gif' alt='' width='14' height='10'> 
					[ <A class='navbar' href='' title=''>SideLink2</A> ]
					<BR/>
					<IMG src='./img/grey_arr.gif' alt='' width='14' height='10'> 
					[ <A class='navbar' href='' title=''>SideLink3</A> ]
					<BR/>
					<IMG src='./img/grey_arr.gif' alt='' width='14' height='10'> 
					[ <A class='navbar' href='' title=''>SideLink4</A> ]
				</SPAN>
			</DIV>
		</DIV> <!-- End: banner -->
	</HEADER> <!-- End: header -->
	<DIV id='stripe' class='darkColorFill'>
		<IMG src='./img/trc.gif' alt=''/>
	</DIV> <!-- End: stripe -->