<BODY class='DEV'>
<!--[if lt IE 7]>
	<P class='chromeframe'>You are using an <strong>outdated</strong> browser. Please <a href='http://browsehappy.com/'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true'>activate Google Chrome Frame</a> to improve your experience.</P>
<![endif]-->

<SCRIPT src='//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js'></SCRIPT>
<!-- <SCRIPT>window.jQuery || document.write('<script src='js/vendor/jquery-1.9.0.min.js'><\/script>')</SCRIPT> -->
<SCRIPT src='js/plugins.js'></SCRIPT>
<SCRIPT src='js/main.js'></SCRIPT>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. 
<SCRIPT>
  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
  s.parentNode.insertBefore(g,s)}(document,'script'));
</SCRIPT>  -->