<!--[if lte IE 6]>
	<LINK rel='stylesheet' />
	<SCRIPT src='js/supersleight/supersleight-min.js'></SCRIPT>
<![endif]-->	
<!--[if lt IE 9]>
	<SCRIPT src='http://html5shiv.googlecode.com/svn/trunk/html5.js'></SCRIPT>
<![endif]-->

	<META charset='utf-8' />
	<TITLE>
		ConspectIS: Template
	</TITLE>

	<META name='Generator' content='EditPlus' />
	<META name='Author' content='Chris Knight' />
	<META name='description' content='ConspectIS is an enterprise datacenter inventory system.' />
	<META name='viewport' content='width=device-width' />
	<LINK rel='stylesheet' href='css/normalize.css' />
	<LINK rel='stylesheet' href='css/main.css' />
	<LINK rel='stylesheet' href='css/conspectis.css' />

	<SCRIPT src='js/main.js'></SCRIPT>
	<SCRIPT src='js/vendor/modernizr-2.6.2.min.js'></SCRIPT>
