	<FOOTER id='footer' class='darkColorFill'>
		<DIV id='footerBox1'>
			<IMG src='./IMG/TRc2.gif' width='11' height='10' alt=''>
		</DIV>
		<DIV id='footerBox2'>
		</DIV>
		<DIV id='footerBox3'>
			<IMG src='./IMG/TRc1.gif' width='11' height='10' alt=''>
		</DIV>
	</FOOTER> <!-- End: footer -->
	<BR/>
	<DIV id='versionTag'>
		<P>
		Powered by ConspectIS <BR/>
		-= Version 0.7 svn 1 (2013-01-24) =-
		</P>
	</DIV> <!-- End: versionTag -->
