	<FOOTER id='popFooter' class='darkColorFill'>
		<DIV id='popFooterBox1'>
			<IMG src='./IMG/TRc2.gif' width='11' height='10' alt=''>
		</DIV>
		<DIV id='popFooterBox2'>
		</DIV>
		<DIV id='popFooterBox3'>
			<IMG src='./IMG/TRc1.gif' width='11' height='10' alt=''>
		</DIV>
	</FOOTER> <!-- End: footer -->
	<BR/>
	<DIV id='versionTag'>
		<P>
		-= Version 3.0 svn 12 (2013-01-24) =-
		</P>
	</DIV> <!-- End: versionTag -->