

<TITLE>USFS Workspace-On-Demand, Version 2</TITLE>
<META HTTP-EQUIV="content-type" CONTENT="text/html; charset=UTF-8" />
<META NAME="description" CONTENT="" />
<META NAME="keywords" CONTENT="" />


<body bgcolor="#FFFFFF" aLink="#004400" link="#006633" vLink="#000000">

<!-- ***** START OF THE MAIN TABLE (#1)... 1 ROW, 2 COLUMNS... 
           LEFT COLUMN CONTAINS PAGE DATA/INFORMATION...
           RIGHT COLUMN CONTAINS THE VERTICAL USDA FOREST SERVICE IMAGE --> 
<table border="" cellspacing="0" cellpadding="0" width="95%" summary="design table only">
  <tr>

<!-- ***** REST OF THE TABLES OCCUR WITHIN THIS LEFT CELL -->

    <td valign="top" align="left"> 
<table width="100%" border="" cellspacing="0" cellpadding="0" summary="design table for page header information">
  <tr> 
    <td bgcolor="#003300" valign="top" align="left"><img src="./img/ct1.gif" alt="" width="19" height="19"></td>
    <td bgcolor="#003300" align="left"><img src="./img/shield_gr.gif" vspace="6" hspace="5" alt="USDA Forest Service Shield" width="50" height="43"></td>
    <td bgcolor="#336633"><img alt="" src="./img/spacer.gif" width="35" height="8">
    <a href="#body" style="color:#336633; font-size:.5em">skipnavbar</a></td>
    <td bgcolor="#669966"><img alt="" src="./img/spacer.gif" width="25" height="8"></td>
    <td width="99%" align="left" valign="top"> 
      <table width="100%" border="" cellspacing="0" cellpadding="0" summary="table containing header navigation bar and page title">
        <tr align="left" valign="top"> 
          <td rowspan="3"><img alt="" src="./img/spacer.gif" width="7" height="8"></td>
          <td colspan="3" id="header_navbar"> 
           
            <span class="xxsverd">
            <a class="navbar" accesskey="h" href="/" title="RO's Intranet Home Page">Home</a> | 
            <a class="navbar" href="http://fsweb.wo.fs.fed.us" title="WO's Intranet Home Page">WO FSweb</a> | 
            <a class="navbar" href="http://www.hqnet.usda.gov/intranet/intranet.htm" title="USDA's Intranet Home Page">USDA Intranet</a> |
            <a class="navbar" href="http://www.usda.gov" title="USDA's Internet Home Page">USDA www</a> | 
            <a class="navbar" href="http://www.fs.fed.us" title="Forest Service's Internet Home Page">FS www</a> | 
            <a class="navbar" href="http://www.fs.fed.us/r3/" title="Southwestern Region's Internet Home Page">R3 www</a> | 
            </span>
           
          </td>
          <!-- ***** THIS IS THE TABLE CELL WHICH CONTAINS THE DIRECTORY LINKS AT TOP OF PAGE --> 
          <!-- ***** END OF DIRECTORY LINKS CELL --> </tr>
        <tr> 
          <td valign="middle" rowspan="2" align="center">
            <img src="./img/r3_logo.gif" width="50" height="50">
          </td>
          <td valign="bottom">
            <img border="" src="./img/wod_titlegif.gif" width="350" height="33">
          </td>
          <td rowspan="2" valign="top" width="40%" align="left" style="background-image: url('./img/circles.gif')">
            <p align="left">
            <img alt="fs intranet" src="./img/3box.gif" vspace="4" hspace="4"></p>
          </td>
        </tr>
        <tr> 
          <td valign="bottom"><span class="subtitle">Southwestern Region - Albuquerque, New Mexico</span></td>
        </tr>
      </table>
    <td align="left"  bgcolor="#edf0f3"><img src="./img/spacer.gif" width="2" height="1" alt=""></td>

  <!-- ***** THIS IS THE TABLE CELL WHICH CONTAINS THE HELP, CONTACT, SEARCH AND SITEMAP LINKS --> 
    <td align="left"  valign="top"><img src="./img/spacer.gif" width="128" height="1" alt=""><BR/>
      <span class="xxsverd"> 
        <img src="./img/grey_arr.gif" alt="" width="14" height="10"> 
     [ <a class="navbar" accesskey="p" href="http://fsweb/fstemplate/help.shtml" title="Find out how to use the FSweb" target="_blank">Help</a> ] <BR/>
        <img src="./img/grey_arr.gif" alt="" width="14" height="10"> 
     [ <a class="navbar" accesskey="c" href="http://fsweb/contact-us.shtml" title="Unit Contact Information - Address, Phone, and Line Officer">Contact Us</a> ] <BR/>
        <img src="./img/grey_arr.gif" alt="" width="14" height="10"> 
     [ <a class="navbar" accesskey="s" href="http://fsweb/search.shtml" title="Search the FSweb">Search</a> ] <BR/>
        <img src="./img/grey_arr.gif" alt="" width="14" height="10"> 
     [ <a class="navbar" accesskey="t" href="http://fsweb/ftp/" title="Link to this unit's File Transfer Protocol (FTP) site">FTP</a> ] </span></td>
   <!-- ***** END OF THE CELL --> </tr>
 </table>

<!-- ***** START OF SPOTLIGHT PROGRAMS TABLE (#3) --> 
     <table width="100%" border="" cellspacing="0" cellpadding="0" bgcolor="#003300" summary="">
        <tr valign="middle" align="left" bgcolor="#003300"> 
          <td colspan="2" bgcolor="#FFFFFF"><img src="./img/spacer.gif" width="139" height="3" alt=""></td>
          <td colspan="2" bgcolor="#FFFFFF" width="99%"><img src="./img/spacer.gif" width="1" height="3" alt=""></td>
        </tr>
        <tr> 
          <td align="center"><img src="./img/spacer.gif" width="1" height="21" alt=""></td>
          <td align="CENTER"></td> 
          <td valign="MIDDLE">
<!-- START OF SPOTLIGHT INCLUDE -->


<!-- END OF SPOTLIGHT INCLUDE -->
	</td>
          <td  bgcolor="#003300" align="right" valign="top"><img src="./img/trc.gif" width="11" height="10" alt=""></td>
        </tr>
        <tr valign="middle" align="left"> 
          <td colspan=4 bgcolor="white"><img src="./img/spacer.gif" width="1" height="3" alt=""></td>
        </tr>
      </table>
<!-- ***** END OF THE SPOTLIGHT PROGRAMS TABLE (#3) --> 

