<table width="100%" border="0" cellspacing="0" cellpadding="0" bgcolor="#003300" summary="">
   <tr valign="middle" align="left"> 
     <td colspan="2" bgcolor="#FFFFFF"><img src="../img/spacer.gif" width="139" height="3" alt=""></td>
     <td colspan="2" bgcolor="#FFFFFF" width="99%"><img src="../img/spacer.gif" width="1" height="3" alt=""></td>
    </tr>
    <tr> 
      <td align="left" valign="top"><img src="../img/trc3.gif" width="11" height="10" alt="" align="top"><img src="../img/spacer.gif" width="1" height="21" alt=""></td>
      <td align="CENTER"></td> 
      <td valign="MIDDLE"></td>
      <td  bgcolor="#003300" align="right" valign="top"><img src="../img/trc.gif" width="11" height="10" alt=""></td>
    </tr>
    <tr valign="middle" align="left"> 
      <td colspan=4 bgcolor="white"><img src="../img/spacer.gif" width="1" height="3" alt=""></td>
    </tr>
</table>