<STYLE>
<!--
   BODY	{
	   font-family:Tahoma, Arial, Sans; 
	   font-size:9pt
	   SCROLLBAR-FACE-COLOR: #336633; 
	   SCROLLBAR-HIGHLIGHT-COLOR: #BBEEBB; 
	   SCROLLBAR-SHADOW-COLOR: #003300; 
	   SCROLLBAR-3DLIGHT-COLOR: #669966; 
	   SCROLLBAR-ARROW-COLOR: #FFCC00; 
	   SCROLLBAR-TRACK-COLOR: #FFFFFF; 
	   SCROLLBAR-DARKSHADOW-COLOR: #000000;
	}
   TD	{font-family:Tahoma, Arial, Sans; font-size:9pt}
   TD.PRINTABLE {font-family:Tahoma, Arial, Sans; font-size:7pt}
   TD.PRINTABLE-HEADING {font-family:Tahoma, Arial, Sans; font-size:8pt}

   A	{color: #ffffff; font-weight: bold}

   A.nodec  {  text-decoration:none }
   A.nodec:hover  {  color: #000000}

   A.changes  {  color: #000000; font-weight: normal; text-decoration:none }
   A.changes:hover  {  color:#336633}

   A.subNodec  {  font-size:8pt; font-style:italic; text-decoration:none }
   A.subNodec:hover  {  color: #000000}

   A.black { text-decoration:none; color:#336633 }
   A.black:hover  {  color: #669966}

   A.yellow { text-decoration:none; color:#ffcc00 }
   A.yellow:hover  {  color: #ffffff}

   A.navbar { color:#336633; font-size:1em; font-family:verdana, arial; font-weight:bold}
   A.navbar:hover {  text-decoration:none; color: #ffcc00}

   HR {  color: #003300; background-color: #003300; height: 3px;}
   HR.DOTTED { background:none;border:none;border-bottom: 3px dashed #003300;}



   H1, H2, H3, H4, H5  {font-family: Arial, Verdana, sans-serif; font-weight: bold}
   H1	{font-size: 140%; color: #003300; font-weight:bold; text-align:center}
   H2	{font-size: 120%; color: #336633; font-weight:bold; text-align:left}
   H3	{font-size: 110%; color: darkgray; font-weight:bold; text-align:left}
   H4	{font-size: 100%; color: darkgray; font-weight:bold; text-align:left}
   .DATATABLE {border-collapse:separate; border-style:solid; 
               border-color:#000000; border-width:2}
   .TABLEHEADING {color: #ffffff; font-size:10pt; font-weight:bold; text-align:center; 
                  background-color:#336633; }
   .LINKTABLE {color: #ffffff; font-size:10pt; font-weight:bold; text-align:center; 
                  background-color:#669966;border-collapse:separate; border-style:solid; 
               border-color:#336633;border-width:2 }
   .BLACKHEADING {color: #ffffff; font-size:12pt; font-weight:bold; text-align:center; 
                  background-color:#000000; }
   .INPUTFORM {color: #ffffff; background-color:#336633; font-weight:bold; text-align:right}
   .ALTROW, .ALTROW TD, .ALTROW TH {background-color:#edf0f3}
   .POPUPDATA {background-color:#bdcebd}

   .CTRTABLE { background-color:#; }
   .CTRTABLE TD { font-family: Arial, Verdana, sans-serif; font-size:9pt; text-align:center}
   .CTRTABLE TH  { font-family: Arial, Verdana, sans-serif; font-size:10pt; font-weight:bold; text-align:left}
   .UNDER { border-collapse:separate; border-bottom-style:solid; border-width:3px; border-color:#000000;}

	
 .title
   { font-size:18pt; font-family:arial,verdana; font-weight: bold }	
 .subtitle 
   { font-size:.8em; font-family:verdana, arial; font-weight:bold; color:#999999 }
 .navheader 
   { font-size:.9em; font-family:arial,verdana; font-weight:bold; color:#FFFFFF }
 .barsep
   { font-size:.6em; font-family:arial,verdana; font-weight:bold; color:#FFFFFF }

/* small verdana */
 .sverd { font-size:1em; font-family:verdana, arial}
/* x-small verdana */
 .xsverd { font-size:.8em; font-family:verdana, arial} 
/* xx-small verdana bold */
 .xsverdb { font-size:.8em; font-family:verdana, arial; font-weight:bold} 
/* xx-small verdana */
 .xxsverd { font-size:.8em; font-family:verdana, arial}
/* xx-small verdana bold */
 .xxsverdb { font-size:.6em; font-family:verdana, arial; font-weight:bold}
/* white xx-small verdana bold */
 .wxxsverdb { font-size:.6em; font-family:verdana, arial; font-weight:bold; color:#FFFFFF }
/* small arial */
 .sarial { font-size:1em; font-family:arial, verdana}
/* small arial bold */
 .sbarial { font-size:1em; font-family:arial, verdana; font-weight:bold}
/* x-small arial */
 .xsarial { font-size:.8em; font-family:arial, verdana}
/* xx-small arial */
 .xxsarial { font-size:.6em; font-family:arial, verdana}
/* white xx-small arial  */
 .wxxsarial { font-size:.6em; font-family:arial, verdana; color:#FFFFFF }

/* use the following to acclompish what they are named */
 .center { text-align:center }
 .underline { text-decoration:underline }
 .strike { text-decoration:line-through }
 .italic { font-style:italic }
 .margin { margin-left: 2cm }
 .wht { color:#FFFFFF }



.xsarialb {  font-family: Arial, Helvetica, sans-serif; font-size: .8em; font-weight: bold}
.content {
	border-top-width: thin;
	border-top-style: solid;
	border-top-color: #009966;
}
-->
</STYLE>